Update convert_systems_csv_to_json.yml
Fix for this error during execution:

```
  /usr/bin/git symbolic-ref HEAD --short
  feat-update-systems-json-2025-11-24
  Working base is branch 'feat-update-systems-json-2025-11-24'
  Error: The 'base' and 'branch' for a pull request must be different branches. Unable to continue.
```

It happens because the workflow is trying to create a pull request from a branch to itself. The branch input is the same as the repository’s default branch (or the base branch).